---
plugin: 
  plugin:
    - PluginClass.php
    - plugin_inc.php
    - schema_plugin_inc.php
    - admin_plugin_inc.php
    - admin_plugin_inc.tpl
    - menu_plugin_admin_inc.tpl
  section:
    - display_section.tpl
    - edit_section_inc.tpl
    - edit_section_mini_inc.tpl
    - menu_plugin_inc.tpl
